# Generated by Django 6.0.3 on 2026-03-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_actors_actor_rename_categories_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
