# Generated by Django 6.0.3 on 2026-03-21 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_movie_movie_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_rating',
            field=models.IntegerField(default=1, help_text='Rate the movie between 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
